### ISSUE TITLE
Feature Request: Package & upload to pypi

### ISSUE THREAD

**Issue by ryanmerolle** [drygdryg/netbox-plugin-interface-sync#1]
https://realpython.com/pypi-publish-python-package/

This makes adding to netbox-docker images or just plain old install on no containerized deployments so much easier.

**Comment by drygdryg** [comment]
The plugin is now avaliable in PyPI. Thanks for the suggestion.

**Comment by ryanmerolle** [comment]
I shared the plugin in the netbox slack since this sort of functionality is asked about all the time by users.
