### ISSUE TITLE
Extend module to support other "components"

### ISSUE THREAD

**Issue by tdrevvatne** [drygdryg/netbox-plugin-interface-sync#3]
While this seems to be an fantastic plugin, to sync network interface from device template to actual device, in a controlled manner..:) - there are also other components in a device template.
Do you have plans to extend the plugin to support other "components"?

**Comment by drygdryg** [comment]
Thanks for the offer, I'll think about it

**Comment by maxzapp** [comment]
I ve testet it with  3.0.6 seems to work, but i really missing sync with  all  physical ports console front rear power etc…
