### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [drygdryg/netbox-plugin-interface-sync#5]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by drygdryg** [comment]
Initial support for NetBox 3.0 implemented: https://github.com/drygdryg/netbox-plugin-interface-sync/tree/netbox-3.0

**Comment by Sislik** [comment]
Hi,

im getting issue when i click the interface sync button:

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.9.7
NetBox version: 3.0.1

**Comment by drygdryg** [comment]
@Sislik, make sure that you have switched to the netbox-3.0 branch before installing the plugin.
```
git clone https://github.com/drygdryg/netbox-plugin-interface-sync -b netbox-3.0
sudo /opt/netbox/venv/bin/pip install ./netbox-plugin-interface-sync
```

**Comment by Sislik** [comment]
thx, that helped :) but now having another issue:
![image](https://user-images.githubusercontent.com/64298143/131829187-8fd775e3-35ab-44ba-aabe-9bc9dbadb2ac.png)
![image](https://user-images.githubusercontent.com/64298143/131829238-9ec9f850-7eee-496b-a4e2-ff485cd84870.png)

**Comment by idrisFoughali** [comment]
> Initial support for NetBox 3.0 implemented: https://github.com/drygdryg/netbox-plugin-interface-sync/tree/netbox-3.0

Any updates on the release date?

**Comment by drygdryg** [comment]
Now you can install version 0.2.0 with NetBox v3.0 support from PyPI:
```
sudo /opt/netbox/venv/bin/pip install netbox-interface-sync
```
